-
  title: "A framework for set-oriented computation in inductive logic programming and its application in generalizing inverse entailment."
  15th ILP Conf. Bonn, Germany, August 2005. 

Optimizing MPF queries: decision support and probabilistic inference. 26th ACM SIGMOD Intl. Conf. on Management of Data. Beijing, China. June 2007.

Tuning regularized kernel estimation parameters for prediction. SIAM Conference on Optimization. Boston, MA.s May 2008.

-
  title: "Model-based quality assessment and base-calling for second-generation sequencing data"
WNAR/IMS annual meeting. Portland, OR, June 2009.

Model-based quality assessment and base-calling for second-generation sequencing data. Conference on Next-Generation Sequencing. Barcelona, October 2009.

Statistical and computational methods for the analysis of pooled, targeted, second-generation re-sequencing data. 8th International Chinese Statistical Association (ICSA) International Conference, Guangzhou, China. December 2010.

Statistical and computational methods for the analysis of pooled, targeted, second-generation re-sequencing data. 2011 Joint Statistical Meetings, Miami Beach, FL., August 2011.


Increased methylation variation in epigenetic domains across cancer types. 16th Annual International Conference on Research in Computational Molecular Biology (RECOMB), April 2012.

Gene expression anti-profiles as a basis for accurate universal cancer signatures. ISMB ’13, July 2013.



Interactive, Exploratory Visualization and Statistical Analysis of Genome-Scale Data. International Biomteric Society ENAR Meeting, Baltimore, March 2014.

Interactive and exploratory visualization of epigenome-wide data. Joint Statistics Meetings, Boston, July 2014.

Epiviz(r): turning a genome browser into a display device. Bioconductor conference, Boston, July 2014.

