
Model-based quality assessment and base-calling for second-generation sequencing data. Third Annual Young Investigators Symposium on Genomics and Bioinformatics. Baltimore MD, September 2009.

Increased methylation variation in epigenetic domains across cancer types. Omics Day, University of Maryland, May 2012.

-
  title: "Srfim2: using basecalling model parameter estimates to understand sequencing bias"
  2012 Joint Statistical Meetings, San Diego, CA, August 2012.

Gene expression network anti-profiles. UMD/NIST Network Science Mini-Symposium, January, 2014.
