-
  title: Interactive visualization in Bioconductor using Epivizr. BioC 2013, Seattle, July 2013.

Interactive visualization for genomic data. NSF DALI workshop on dynamic languages for scalable data analytics. Indianapolis, November 2013.
